### PR TITLE
For applications using histogram fluxes account for deficiency in GetRandom() if variable bin widths

### PR DESCRIPTION
**Pull request by nusense**
Histograms with variable bin widths are not properly sampled by TH1D::GetRandom() -- only by height not by area so re-fill any variable bin width histograms with contents*width before handing them to the flux driver.  This is conditional on ROOT_VERSION < 9.99.99 which can be changed if in the future the behavior is corrected.

### CODE REVIEW

**Comment by mroda88** [comment]
Do we need to have this in for 3.02.00 ?
Trying to understand if it means I have to retag 3.01

**Comment by candreop** [comment]
oh! Didn't realise there was a problem (or a misunderstanding of what it was meant to do) with GetRandom() in ROOT. Perhaps it is worth checking other occurences of this in GENIE. Most likely, in these other contexts, it is not used with variable bin histograms but it is worth doing some quick check and even add some comments in the code so that this doesn't get forgotten. Will try to do this once I get a moment, but for now I will just leave this here:

Costass-MBP:src costas$ grep -R GetRandom ./*
./Apps/gEvGenHadronNucleus.cxx:  if(gOptUsingFlux) return gSpectrum->GetRandom(); // spectrum
./Apps/gUpMuFluxGen.cxx:    brEmu        = pdfEmu->GetRandom();
./Physics/Coherent/EventGen/COHKinematicsGenerator.cxx:      fEnvelope->GetRandom2(gx,gy);
./Physics/NuclearState/EffectiveSF.cxx:    double p = prob->GetRandom();
./Physics/NuclearState/FGMBodekRitchie.cxx:  double p = prob->GetRandom();
./Physics/NuclearState/LocalFGM.cxx:  double p = prob->GetRandom();
./Physics/Resonance/EventGen/RESKinematicsGenerator.cxx:         fEnvelope->GetRandom2(gQD2,gW);
./Physics/Hadronization/CollinsSpillerFragm.cxx:  return fFunc->GetRandom();
./Physics/Hadronization/PetersonFragm.cxx:  return fFunc->GetRandom();
./Physics/Hadronization/AGCharm2019.cxx:     double ptc2 = fCharmPT2pdf->GetRandom();
./Physics/Hadronization/AGKYLowW2019.cxx:    mult = TMath::Nint( mprob->GetRandom() );
./Physics/Hadronization/AGKYLowW2019.cxx:      double xf  = fBaryonXFpdf ->GetRandom();
./Physics/Hadronization/AGKYLowW2019.cxx:      double pt2 = fBaryonPT2pdf->GetRandom();
./Tools/Flux/GAtmoFlux.cxx:     fTotalFluxHisto->GetRandom3(ax, ay, az);
./Tools/Flux/GAstroFlux.cxx:       log10E = log10Epdf.GetRandom();
./Tools/Flux/GAstroFlux.cxx:     opdf.GetRandom2(phi,costheta);
./Tools/Flux/GCylindTH1Flux.cxx:  double Ev = (double) fTotSpectrum->GetRandom();
./Tools/Flux/GCylindTH1Flux.cxx:  double Rt = fRtDep->GetRandom(); // rndm R [0,Rtransverse]
./contrib/test/gtestROOTGeometry.cxx:void GetRandomRay       (TLorentzVector & x, TLorentzVector & p);
./contrib/test/gtestROOTGeometry.cxx:    GetRandomRay(x,p);
./contrib/test/gtestROOTGeometry.cxx:void GetRandomRay(TLorentzVector & x, TLorentzVector & p)

**Comment by nusense** [comment]
I'm not sure this warrants a re-tag.  Or at most just tagging R-3_01_01 but I double anyone who's going to exercise R-3_01_00 between now and tagging R-3_02_00 is going to exercise this feature of the applications.

Its been doubly wrong since the beginning of time [rebooked the histogram under the assumption of fixed bins -- which I fixed with TH1D::Clone(); then this misinterpretation of how GetRandom() worked] so none of these apps should ever have been used with variable width histograms before now.   I had a user try once with gevgen_fnal (which lead me to fix the rebook to use Clone() and then I thought I was done because that was the "fix" to gevgen that was previously made) issue, to very screwy results.  This corner of the code isn't heavily utilized so I think just fixing it is fine without worrying too much about tags.

As for the other instances of uses of GetRandom() on TH1D that are buried deeper in the code, I'd hope we'd have noticed but I guess we should review them as well. But lets make that a separate issue/pull request.

**Comment by mroda88** [comment]
Great, thanks. So I'll merge this and that's all for now.

**Pull request merged**
