### PR TITLE
Develop/nuclear tune cmc

### PR DESCRIPTION
**Pull request by jtenavidal**
Place holder for nuclear tunes from https://arxiv.org/abs/2206.11050

Instructions on how to configure different tunes are provided. By default we use MINERvA's tune parameters (G30a)

Need to discuss tune naming scheme

### CODE REVIEW

**Review by mroda88 — COMMENTED** [review]
can we change the beginning of tune name? GEPJ18_bla shall do.

**Comment by jtenavidal** [comment]
> can we change the beginning of tune name? GEPJ18_bla shall do.

Yes, I'm waiting to get the paper number. The paper should be published soon. It should be in Phys.Rev.D, but I don't know the number yet.

**Comment by jtenavidal** [comment]
Status: 
Running some splines for testing

**Comment by jtenavidal** [comment]
I run the test and got the same plots presented in the paper. The new example configurations can be merged.

**Review by mroda88 — APPROVED** [review]
LGTM

**Pull request merged**
