### PR TITLE
Update ReinSehgalRESPXSec.cxx

### PR DESCRIPTION
**Pull request by idkakorin**
The EM-factor should be as for KLNBS model.

### CODE REVIEW

**Comment by idkakorin** [comment]
Please, see the Eq.(4) of [preprint](https://arxiv.org/pdf/2009.07228)

**Comment by idkakorin** [comment]
@jtenavidal It is something strange, because the factor_new/factor_old=16\sin^4\theta_Weinberg. It is about 15-20% difference. The same difference should be in cross-sections.

**Comment by jtenavidal** [comment]
Hi Igor, I re-run both with the same inputs and now I get exactly the same. I run your code as follows:
```
source setup_GENIE.sh https://github.com/GENIE-MC/Generator.git idkakorin-patch-1 ;
gmkspl -p 11 -t 1000000010 -n 100 -e 15 --tune G18_10a_00_000 -o e_on_n_EMRES.xml --event-generator-list EMRES ;
```

and the master code as: 
```
source setup_GENIE.sh https://github.com/GENIE-MC/Generator.git master ;
gmkspl -p 11 -t 1000000010 -n 100 -e 15 --tune G18_10a_00_000 -o e_on_n_EMRES.xml --event-generator-list EMRES ;
```

The `setup_GENIE.sh` file contains the code to pull it from git and set the right branch. In short, :
```
git clone https://github.com/GENIE-MC/Generator.git Generator/ 
cd Generator
git checkout "idkakorin-patch-1" 
```
Then it builds the code from scratch...

**Comment by jtenavidal** [comment]
Hi Igor, I re-run both with the same inputs and now I get exactly the same. I run your code as follows:
```
source setup_GENIE.sh https://github.com/GENIE-MC/Generator.git idkakorin-patch-1 ;
gmkspl -p 11 -t 1000000010 -n 100 -e 15 --tune G18_10a_00_000 -o e_on_n_EMRES.xml --event-generator-list EMRES ;
```

and the master code as: 
```
source setup_GENIE.sh https://github.com/GENIE-MC/Generator.git master ;
gmkspl -p 11 -t 1000000010 -n 100 -e 15 --tune G18_10a_00_000 -o e_on_n_EMRES.xml --event-generator-list EMRES ;
```

The `setup_GENIE.sh` file contains the code to pull it from git and set the right branch. In short, :
```
git clone https://github.com/GENIE-MC/Generator.git Generator/ 
cd Generator
git checkout "idkakorin-patch-1" 
```
Then it builds the code from scratch... 
Please correct me if i am wrong but the code above also affects the BS code right? I can't find it right now but I believe it inherits from it

**Comment by jtenavidal** [comment]
image

This is the effect on e-+n (RES). The change only affects the G18_01a configuration, which is not used

**Comment by jtenavidal** [comment]
image
With this change, the RS and BS predictions are consistent (black (G18_10a) and blue(G18_01a) )

**Comment by idkakorin** [comment]
Now the difference is as it should be.

**Review by jtenavidal — APPROVED** [review]

**Pull request merged**
